version: '3.8'

services:
  app:
    build: .
    ports:
      - '${PORT:-5000}:5000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    env_file:
      - .env
    depends_on:
      - mongo
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 30s # how often to run the check
      timeout: 10s # how long to wait for response
      retries: 3 # retry count before considering unhealthy
      start_period: 10s # grace period before healthchecks start

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
